# Build workflow for GitHub actions

name: Build & test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
    
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
  
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Restore packages
          run: dotnet restore src/Acumen.sln

        - name: Build
          run: dotnet build --no-restore src/Acumen.sln
          
        - name: Test
          run: dotnet test --no-build --verbosity normal src/Acumen.Tests/Acumen.Tests.csproj